<?php
include('config.php');
// $phoneNumber = "13812345678";
// $message = 'This message was generated by curl and php';
// $curlPost = 'pNUMBER=' . urlencode($phoneNumber) . '&MESSAGE=' . urlencode($message) . '&SUBMIT=Send';
// $ch = curl_init();
// curl_setopt($ch, CURLOPT_URL, 'http://localhost/new2015php/New/getPost.php');
// curl_setopt($ch, CURLOPT_HEADER, 1);
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// curl_setopt($ch, CURLOPT_POST, 1);
// curl_setopt($ch, CURLOPT_POSTFIELDS, $curlPost);
// $data = curl_exec($ch);
// curl_close($ch);
// dump($data);

//===============2
// $urlcon= 'http://localhost/new2015php/New/getPost.php';
// $data='{
// "button":[
// {
// "type":"click",
// "name":"今日歌曲",
// "key":"V1001_TODAY_MUSIC"
// },
// {
// "type":"click",
// "name":"歌手简介",
// "key":"V1001_TODAY_SINGER"
// },
// {
// "name":"菜单",
// "sub_button":[
// {
// "type":"click",
// "name":"hello word",
// "key":"V1001_HELLO_WORLD"
// },
// {
// "type":"click",
// "name":"赞一下我们",
// "key":"V1001_GOOD"
// }]
// }]
// }';
// $host = $urlcon;
// $ch = curl_init();
// $data = 'data='.$data;
// curl_setopt($ch, CURLOPT_URL,$host);
// curl_setopt($ch, CURLOPT_HEADER, 1);
// curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
// curl_setopt($ch, CURLOPT_POST, 1);
// curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
// $output = curl_exec($ch);
// echo $output;
// curl_close($ch);

//=========4
// $url = "http://localhost/new2015php/New/getPost.php";
// $post_data = array ("username" => "bob","key" => "12345");
// $ch = curl_init();
// curl_setopt($ch, CURLOPT_URL, $url);
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// // post数据
// curl_setopt($ch, CURLOPT_POST, 1);
// // post的变量
// curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);

// $output = curl_exec($ch);
// curl_close($ch);

// //打印获得的数据
// print_r($output);

//=======5
// $output_news = array('name'=>'caiknife', 'email'=>'caiknife@gmail.com');
// $post_url = "http://localhost/new2015php/New/getPost.php";
// $post_data = json_encode($output_news);//$output_news处理好的数组
// $ch = curl_init();//初始化
// curl_setopt($ch, CURLOPT_TIMEOUT, '30');//超时时间
// curl_setopt($ch, CURLOPT_HTTPHEADER, array('Keep-Alive: 300','Connection: keep-alive'));   //自定义请求头信息
// curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; GTB7.4; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2)');
// curl_setopt($ch, CURLOPT_POST,1);
// curl_setopt($ch, CURLOPT_URL,$post_url);
// curl_setopt($ch, CURLOPT_POSTFIELDS,"news=".$post_data);
// $contents = curl_exec($ch);
// if(curl_errno($ch)){//出错则显示错误信息
// print curl_error($ch);
// }
// curl_close($ch);
// dump($contents);

// function curl_post($url, $post) {  
//     $options = array(  
//         CURLOPT_RETURNTRANSFER => true,  
//         CURLOPT_HEADER         => false,  
//         CURLOPT_POST           => true,  
//         CURLOPT_POSTFIELDS     => $post,  
//     );  
  
//     $ch = curl_init($url);  
//     curl_setopt_array($ch, $options);  
//     $result = curl_exec($ch);  
//     curl_close($ch);  
//     return $result;  
// }  
  
// $data = curl_post("http://localhost/new2015php/New/getPost.php", array('name'=>'caiknife', 'email'=>'caiknife@gmail.com'));  
  
// var_dump($data);